# Permalinks
permalink:           pretty

# Setup
title:               Wyko Rijnsburger
url:                 https://www.wykorijnsburger.nl
paginate:            5
baseurl:             ""
analytics_id:        UA-92037356-1
# About/contact
author:
  name:              Wyko Rijnsburger
  url:               https://www.wykorijnsburger.nl
  email:             utwyko@gmail.com

pages_list:
  About: '/about'
  Feed: '/atom.xml'

# Custom vars
version:             3.0.0
github:
  repo:              https://github.com/utwyko/utwyko.github.io


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag